from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .loader import Compendium

EXPECTED_BASE_CLASSES = {
    "barbarian",
    "bard",
    "cleric",
    "druid",
    "fighter",
    "monk",
    "paladin",
    "ranger",
    "rogue",
    "sorcerer",
    "warlock",
    "wizard",
}

EXPECTED_CORE_CONDITIONS = {
    "blinded",
    "charmed",
    "deafened",
    "exhaustion",
    "frightened",
    "grappled",
    "incapacitated",
    "invisible",
    "paralyzed",
    "petrified",
    "poisoned",
    "prone",
    "restrained",
    "stunned",
    "unconscious",
}

EXPECTED_PHASE1_HAZARDS = {
    "srd.burning",
    "srd.burning_oil",
    "srd.deep_water",
    "srd.dehydration",
    "srd.extreme_cold",
    "srd.extreme_heat",
    "srd.falling_10ft",
    "srd.falling_30ft",
    "srd.malnutrition",
    "srd.strong_wind",
    "srd.suffocation",
}

EXPECTED_PHASE1_ACTIONS = {
    "srd.action_surge",
    "srd.agonizing_blast",
    "srd.ascendant_step",
    "srd.ascendant_step_levitate",
    "srd.armor_of_shadows",
    "srd.armor_of_shadows_mage_armor",
    "srd.aura_of_courage",
    "srd.barbarian_unarmored_defense",
    "srd.bard_expertise",
    "srd.bardic_inspiration",
    "srd.cure_wounds",
    "srd.cunning_strike",
    "srd.cunning_action_dash",
    "srd.cunning_action_disengage",
    "srd.cunning_action_hide",
    "srd.cutting_words",
    "srd.dark_ones_blessing",
    "srd.danger_sense",
    "srd.dash",
    "srd.deft_explorer",
    "srd.deflect_energy",
    "srd.devils_sight",
    "srd.disengage",
    "srd.disciple_of_life",
    "srd.dodge",
    "srd.draconic_resilience",
    "srd.eldritch_invocations",
    "srd.eldritch_mind",
    "srd.eldritch_smite",
    "srd.eldritch_spear",
    "srd.divine_order",
    "srd.divine_spark_heal",
    "srd.divine_spark_necrotic",
    "srd.divine_spark_radiant",
    "srd.divine_sense",
    "srd.divine_smite",
    "srd.disciplined_survivor",
    "srd.druidic",
    "srd.extra_attack",
    "srd.favored_enemy_hunters_mark",
    "srd.faithful_steed",
    "srd.faithful_steed_find_steed",
    "srd.fast_hands_magic_item",
    "srd.fast_hands_sleight_of_hand",
    "srd.fast_hands_utilize",
    "srd.fiendish_vigor",
    "srd.fiendish_vigor_false_life",
    "srd.fleet_step",
    "srd.flurry_of_blows",
    "srd.quivering_palm",
    "srd.quivering_palm_release",
    "srd.font_of_inspiration_restore_bardic_inspiration_slot_1",
    "srd.font_of_inspiration_restore_bardic_inspiration_slot_2",
    "srd.font_of_inspiration_restore_bardic_inspiration_slot_3",
    "srd.frenzy",
    "srd.font_of_magic_convert_slot_1",
    "srd.font_of_magic_convert_slot_2",
    "srd.font_of_magic_convert_slot_3",
    "srd.font_of_magic_create_slot_1",
    "srd.font_of_magic_create_slot_2",
    "srd.font_of_magic_create_slot_3",
    "srd.gaze_of_two_minds",
    "srd.gaze_of_two_minds_touch",
    "srd.gift_of_the_depths",
    "srd.gift_of_the_depths_water_breathing",
    "srd.help",
    "srd.heightened_focus",
    "srd.hide",
    "srd.hunters_lore",
    "srd.hunters_prey_colossus_slayer",
    "srd.hunters_prey_horde_breaker",
    "srd.improved_cunning_strike",
    "srd.improved_critical",
    "srd.investment_of_the_chain_master",
    "srd.innate_sorcery",
    "srd.lay_on_hands",
    "srd.lay_on_hands_remove_poisoned",
    "srd.lands_aid",
    "srd.lessons_of_the_first_ones",
    "srd.longsword_attack",
    "srd.magical_cunning",
    "srd.master_of_myriad_forms",
    "srd.master_of_myriad_forms_alter_self",
    "srd.mask_of_many_faces",
    "srd.mask_of_many_faces_disguise_self",
    "srd.memorize_spell",
    "srd.misty_visions",
    "srd.misty_visions_silent_image",
    "srd.martial_arts_bonus_unarmed_strike",
    "srd.move",
    "srd.monk_unarmed_strike",
    "srd.monk_unarmored_defense",
    "srd.monk_unarmored_movement",
    "srd.one_with_shadows",
    "srd.one_with_shadows_invisibility",
    "srd.open_hand_technique",
    "srd.opportunity_attack",
    "srd.otherworldly_leap",
    "srd.otherworldly_leap_jump",
    "srd.pact_of_the_blade",
    "srd.pact_of_the_blade_weapon",
    "srd.pact_of_the_chain",
    "srd.pact_of_the_chain_find_familiar",
    "srd.pact_of_the_tome",
    "srd.patient_defense",
    "srd.patient_defense_focus",
    "srd.paladins_smite_divine_smite",
    "srd.perfect_focus",
    "srd.potent_cantrip",
    "srd.primal_order",
    "srd.rage",
    "srd.preserve_life",
    "srd.primal_knowledge",
    "srd.reckless_attack",
    "srd.reliable_talent",
    "srd.remarkable_athlete",
    "srd.repelling_blast",
    "srd.ritual_adept",
    "srd.rogue_expertise",
    "srd.sacred_weapon",
    "srd.scholar",
    "srd.second_wind",
    "srd.second_story_work",
    "srd.shortsword_attack",
    "srd.slow_fall",
    "srd.sneak_attack",
    "srd.sorcerous_restoration",
    "srd.steady_aim",
    "srd.stunning_strike",
    "srd.superior_defense",
    "srd.step_of_the_wind",
    "srd.step_of_the_wind_focus",
    "srd.thieves_cant",
    "srd.thirsting_blade",
    "srd.turn_undead",
    "srd.uncanny_metabolism",
    "srd.uncanny_dodge",
    "srd.wild_companion_spell_slot",
    "srd.wild_companion_wild_shape",
    "srd.wild_resurgence_create_spell_slot",
    "srd.wild_resurgence_restore_wild_shape_slot_1",
    "srd.wild_resurgence_restore_wild_shape_slot_2",
    "srd.wild_resurgence_restore_wild_shape_slot_3",
    "srd.wild_shape_giant_rat",
    "srd.wild_shape_wolf",
}

EXPECTED_PHASE1_MONSTERS = {
    "srd.bandit",
    "srd.bandit_captain",
    "srd.cultist",
    "srd.giant_rat",
    "srd.kobold",
    "srd.warrior_infantry",
    "srd.skeleton",
    "srd.wolf",
    "srd.zombie",
}

EXPECTED_PHASE1_ITEMS = {
    "srd.arcane_focus",
    "srd.chain_mail",
    "srd.dagger",
    "srd.explorers_pack",
    "srd.handaxe",
    "srd.healers_kit",
    "srd.holy_symbol",
    "srd.leather_armor",
    "srd.light_crossbow",
    "srd.longsword",
    "srd.mace",
    "srd.quarterstaff",
    "srd.rations_day",
    "srd.rope_50ft",
    "srd.shield",
    "srd.shortbow",
    "srd.shortsword",
    "srd.spear",
    "srd.thieves_tools",
    "srd.torch",
    "srd.potion_of_healing",
    "srd.poisoners_kit",
}

EXPECTED_PHASE1_SPELLS = {
    "srd.spell.acid_arrow",
    "srd.spell.acid_splash",
    "srd.spell.aid",
    "srd.spell.alarm",
    "srd.spell.alter_self",
    "srd.spell.animal_friendship",
    "srd.spell.animal_messenger",
    "srd.spell.animate_dead",
    "srd.spell.arcane_lock",
    "srd.spell.arcanists_magic_aura",
    "srd.spell.augury",
    "srd.spell.bane",
    "srd.spell.barkskin",
    "srd.spell.beacon_of_hope",
    "srd.spell.bestow_curse",
    "srd.spell.bless",
    "srd.spell.blindness_deafness",
    "srd.spell.blink",
    "srd.spell.blur",
    "srd.spell.burning_hands",
    "srd.spell.call_lightning",
    "srd.spell.calm_emotions",
    "srd.spell.charm_person",
    "srd.spell.chill_touch",
    "srd.spell.chromatic_orb",
    "srd.spell.clairvoyance",
    "srd.spell.color_spray",
    "srd.spell.command",
    "srd.spell.comprehend_languages",
    "srd.spell.conjure_animals",
    "srd.spell.continual_flame",
    "srd.spell.counterspell",
    "srd.spell.create_food_and_water",
    "srd.spell.create_or_destroy_water",
    "srd.spell.cure_wounds",
    "srd.spell.dancing_lights",
    "srd.spell.darkness",
    "srd.spell.darkvision",
    "srd.spell.daylight",
    "srd.spell.detect_evil_and_good",
    "srd.spell.detect_magic",
    "srd.spell.detect_poison_and_disease",
    "srd.spell.detect_thoughts",
    "srd.spell.disguise_self",
    "srd.spell.dispel_magic",
    "srd.spell.dissonant_whispers",
    "srd.spell.divine_favor",
    "srd.spell.divine_smite",
    "srd.spell.dragons_breath",
    "srd.spell.druidcraft",
    "srd.spell.elementalism",
    "srd.spell.eldritch_blast",
    "srd.spell.enhance_ability",
    "srd.spell.enlarge_reduce",
    "srd.spell.ensnaring_strike",
    "srd.spell.entangle",
    "srd.spell.enthrall",
    "srd.spell.expeditious_retreat",
    "srd.spell.faerie_fire",
    "srd.spell.false_life",
    "srd.spell.fear",
    "srd.spell.feather_fall",
    "srd.spell.find_familiar",
    "srd.spell.find_steed",
    "srd.spell.find_traps",
    "srd.spell.fire_bolt",
    "srd.spell.fireball",
    "srd.spell.flame_blade",
    "srd.spell.flaming_sphere",
    "srd.spell.floating_disk",
    "srd.spell.fly",
    "srd.spell.fog_cloud",
    "srd.spell.gaseous_form",
    "srd.spell.gentle_repose",
    "srd.spell.glyph_of_warding",
    "srd.spell.goodberry",
    "srd.spell.grease",
    "srd.spell.guidance",
    "srd.spell.guiding_bolt",
    "srd.spell.gust_of_wind",
    "srd.spell.haste",
    "srd.spell.healing_word",
    "srd.spell.heat_metal",
    "srd.spell.hellish_rebuke",
    "srd.spell.heroism",
    "srd.spell.hex",
    "srd.spell.hideous_laughter",
    "srd.spell.hold_person",
    "srd.spell.hunters_mark",
    "srd.spell.hypnotic_pattern",
    "srd.spell.ice_knife",
    "srd.spell.identify",
    "srd.spell.illusory_script",
    "srd.spell.inflict_wounds",
    "srd.spell.invisibility",
    "srd.spell.jump",
    "srd.spell.knock",
    "srd.spell.lesser_restoration",
    "srd.spell.levitate",
    "srd.spell.light",
    "srd.spell.lightning_bolt",
    "srd.spell.locate_animals_or_plants",
    "srd.spell.locate_object",
    "srd.spell.longstrider",
    "srd.spell.mage_armor",
    "srd.spell.mage_hand",
    "srd.spell.magic_circle",
    "srd.spell.magic_missile",
    "srd.spell.magic_mouth",
    "srd.spell.magic_weapon",
    "srd.spell.major_image",
    "srd.spell.mass_healing_word",
    "srd.spell.meld_into_stone",
    "srd.spell.mending",
    "srd.spell.message",
    "srd.spell.mind_spike",
    "srd.spell.minor_illusion",
    "srd.spell.mirror_image",
    "srd.spell.misty_step",
    "srd.spell.moonbeam",
    "srd.spell.nondetection",
    "srd.spell.pass_without_trace",
    "srd.spell.phantasmal_force",
    "srd.spell.phantom_steed",
    "srd.spell.plant_growth",
    "srd.spell.poison_spray",
    "srd.spell.prayer_of_healing",
    "srd.spell.prestidigitation",
    "srd.spell.produce_flame",
    "srd.spell.protection_from_energy",
    "srd.spell.protection_from_evil_and_good",
    "srd.spell.protection_from_poison",
    "srd.spell.purify_food_and_drink",
    "srd.spell.ray_of_enfeeblement",
    "srd.spell.ray_of_frost",
    "srd.spell.ray_of_sickness",
    "srd.spell.remove_curse",
    "srd.spell.resistance",
    "srd.spell.revivify",
    "srd.spell.rope_trick",
    "srd.spell.sacred_flame",
    "srd.spell.sanctuary",
    "srd.spell.scorching_ray",
    "srd.spell.searing_smite",
    "srd.spell.see_invisibility",
    "srd.spell.sending",
    "srd.spell.shatter",
    "srd.spell.shield",
    "srd.spell.shield_of_faith",
    "srd.spell.shillelagh",
    "srd.spell.shining_smite",
    "srd.spell.shocking_grasp",
    "srd.spell.silence",
    "srd.spell.silent_image",
    "srd.spell.sleep",
    "srd.spell.sleet_storm",
    "srd.spell.slow",
    "srd.spell.sorcerous_burst",
    "srd.spell.spare_the_dying",
    "srd.spell.speak_with_animals",
    "srd.spell.speak_with_dead",
    "srd.spell.speak_with_plants",
    "srd.spell.spider_climb",
    "srd.spell.spike_growth",
    "srd.spell.spirit_guardians",
    "srd.spell.spiritual_weapon",
    "srd.spell.starry_wisp",
    "srd.spell.stinking_cloud",
    "srd.spell.suggestion",
    "srd.spell.thaumaturgy",
    "srd.spell.thunderwave",
    "srd.spell.tiny_hut",
    "srd.spell.tongues",
    "srd.spell.true_strike",
    "srd.spell.unseen_servant",
    "srd.spell.vampiric_touch",
    "srd.spell.vicious_mockery",
    "srd.spell.warding_bond",
    "srd.spell.water_breathing",
    "srd.spell.water_walk",
    "srd.spell.web",
    "srd.spell.wind_wall",
    "srd.spell.zone_of_truth",
}


@dataclass(frozen=True)
class CoverageSection:
    name: str
    loaded_count: int
    expected_count: int | None = None
    missing: list[str] = field(default_factory=list)
    complete: bool = False
    note: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "loaded_count": self.loaded_count,
            "expected_count": self.expected_count,
            "missing": self.missing,
            "complete": self.complete,
            "note": self.note,
        }


@dataclass(frozen=True)
class CompendiumCoverageReport:
    sections: list[CoverageSection]

    @property
    def fully_complete(self) -> bool:
        return all(section.complete for section in self.sections)

    def to_dict(self) -> dict[str, Any]:
        return {
            "fully_complete": self.fully_complete,
            "sections": [section.to_dict() for section in self.sections],
        }


def build_coverage_report(compendium: Compendium) -> CompendiumCoverageReport:
    class_ids = set(compendium.classes)
    condition_ids = set(compendium.conditions)
    hazard_ids = set(compendium.hazards)
    return CompendiumCoverageReport(
        sections=[
            _expected_set_section("base_classes", class_ids, EXPECTED_BASE_CLASSES),
            _expected_set_section("core_conditions", condition_ids, EXPECTED_CORE_CONDITIONS),
            _expected_set_section(
                "spells_0_to_3",
                {
                    spell_id
                    for spell_id, spell in compendium.spells.items()
                    if int(spell.level) <= 3
                },
                EXPECTED_PHASE1_SPELLS,
                note="Phase 1 requires all SRD cantrips and level 1-3 spells.",
            ),
            _expected_set_section(
                name="actions",
                loaded=set(compendium.actions),
                expected=EXPECTED_PHASE1_ACTIONS,
                note=(
                    "Phase 1 requires executable M4-2 base actions plus "
                    "opportunity and extra attack support."
                ),
            ),
            _expected_set_section(
                name="monsters",
                loaded=set(compendium.monsters),
                expected=EXPECTED_PHASE1_MONSTERS,
                note="Phase 1 requires the representative Tier 1 encounter stat blocks.",
            ),
            _expected_set_section(
                name="items",
                loaded=set(compendium.items),
                expected=EXPECTED_PHASE1_ITEMS,
                note="Phase 1 requires starter weapons, armor, tools, foci, and adventuring gear.",
            ),
            _expected_set_section(
                name="hazards",
                loaded=hazard_ids,
                expected=EXPECTED_PHASE1_HAZARDS,
                note="Phase 1 requires the core SRD environmental hazards named in tasks.md.",
            ),
        ]
    )


def _expected_set_section(
    name: str,
    loaded: set[str],
    expected: set[str],
    *,
    note: str = "",
) -> CoverageSection:
    missing = sorted(expected - loaded)
    return CoverageSection(
        name=name,
        loaded_count=len(loaded),
        expected_count=len(expected),
        missing=missing,
        complete=not missing,
        note=note,
    )
